apiVersion: v1        #步驟一
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity: 
    storage: 5Gi      #use EFS capacity so storage capacity doesn't matter
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: ""          #新版不用+了
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0f699b39f9f08cf97    #自己的EFS File System ID
---
apiVersion: v1                         #步驟二
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-api
          image: coastk05396/kub-dep-users:latest
          env:
            - name: MONGODB_CONNECTION_URI
              value: 'mongodb+srv://root:hsip0607@cluster0.gkt92fv.mongodb.net/k8saws?retryWrites=true&w=majority'
            - name: AUTH_API_ADDRESSS
              value: 'auth-service.default:3000'
          volumeMounts:                  #步驟四(Mount Container Volume)
            - name: efs-vol
              mountPath: /app/users     
      volumes:                           #步驟三(連接Pod Volume)
        - name: efs-vol                  
          persistentVolumeClaim:
            claimName: efs-pvc           # 拿取步驟二PVC 

